/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Domains } from "./Domains";
export type { HogwartsStudentsService } from "./HogwartsStudentsService";
