/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Domains } from "./Domains";
export * as factories from "./factories";
export { Domains__factory } from "./factories/Domains__factory";
